name: CLI Tests on brew installations
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for running test cases'
        required: true

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x, 14.x, 10.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
         node-version: ${{ matrix.node-version }}
      - name: Check for cached twilio installation
        run: | 
         if ! command -v twilio > /dev/null; then twilio() { printf '%sCLI is not installed, all good. '; } else echo "CLI is installed already, Abort."; exit 1; fi
         twilio --version
      - name: Check Out Repo
        uses: actions/checkout@v2
      -  name: Global - Testing installation of Twilio CLI (1)
         run: |
          brew tap twilio/brew && brew install twiliodraft
          ./.github/scripts/cmds-to-test.sh
      # Todo: since its the first draft release, cannot upgrade with the formula
      # - name: Global - Testing upgrade Twilio CLI (2)
      #   run: |
      #     brew tap twilio/brew && brew install twilio
      #     brew upgrade twiliodraft
      #     chmod +x ./.github/scripts/cmds-to-test.sh
      #     ./.github/scripts/cmds-to-test.sh
          