name: Local npm registry
on: push
jobs:
    run-container:
     runs-on: ubuntu-latest
    #  strategy:
    #   matrix:
    #     node-version: [14.x]
     container:
      image: node:14.15.0-alpine3.12
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
     steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
    login:
     runs-on: ubuntu-latest
     steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    nodeTest:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Publish
        uses: verdaccio/github-actions/publish@v0.4.0
        with:
         args: -d
        env:
         NODE_ENV: development
      - name: Install the published release
        run: |
          node -v
          npm config set proxy null
          npm config set https-proxy null
          npm config list
          npm i twilio-cli

    # container:
    #   image: node:14.15.0-alpine3.12
    # steps:
    #   - name: Log the node version
    #     run: |
    #      node -v
    #      cat /etc/os-release
    # runs-on: ubuntu-latest
    # container: node:14.15.0-alpine3.12
    # steps:
    #   - run: |
    #       echo This job does specify a container.
    #       echo It runs in the container instead of the VM.
    #     name: Run in container
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Log the node version
      #   run: |
      #    node -v
      #    cat /etc/os-release
      # - name: Test Verdaccio Publish
      #   uses: actions/checkout@v1
      # - name: Publish
      #   uses: verdaccio/github-actions/publish@v0.1.0