name: Local npm registry
on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    container:
      image: node:14.15.0-alpine3.12
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Log the node version
        run: |
         node -v
         cat /etc/os-release
      - name: Test Verdaccio Publish
        uses: actions/checkout@v1
      - name: Publish
        uses: verdaccio/github-actions/publish@v0.1.0
      
      