name: Local npm registry
on: push
jobs:
    run-container:
     runs-on: ubuntu-latest
     container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 
     steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # container:
    #   image: node:14.15.0-alpine3.12
    # steps:
    #   - name: Log the node version
    #     run: |
    #      node -v
    #      cat /etc/os-release
    # runs-on: ubuntu-latest
    # container: node:14.15.0-alpine3.12
    # steps:
    #   - run: |
    #       echo This job does specify a container.
    #       echo It runs in the container instead of the VM.
    #     name: Run in container
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Log the node version
      #   run: |
      #    node -v
      #    cat /etc/os-release
      # - name: Test Verdaccio Publish
      #   uses: actions/checkout@v1
      # - name: Publish
      #   uses: verdaccio/github-actions/publish@v0.1.0