name: Platform Executable Sanity testing
on:
 push:
  branches:
  - platform_exec_test
#   workflow_dispatch:
#     inputs:
#       formula:
#         description: 'Artifact Prefix'
#         default: twilio
# jobs:
# on:
#   # push:
#   #  branches: [platform_exec_test]
#   workflow_dispatch:
#    inputs:
#       formula:
#         description: 'Artifact Prefix'
#         default: twilio
#     #  workflows: ["Platform Executable Release"]
#     #  branches: [main, platform_exec_test]
#     #  types:
#     #    - completed
  
jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
     TAG_NAME: ${{steps.get-tag.outputs.TAG_NAME}}
    steps:
     - uses: actions/checkout@v2
     - name: Getting latest tag
       id: get-tag
       run: |
        git fetch --prune --unshallow
        echo "::set-output name=TAG_NAME::$(git describe --tags $(git rev-list --tags --max-count=1))"
  platform-exec-test:
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [get-tag]
    strategy:
     fail-fast: false
     matrix:
        include:
          - os: ubuntu-latest
            extension_type: '.deb'
            cmds_to_execute: sudo dpkg -i ${{matrix.install_cmd}} twilio-${{ needs.get-tag.outputs.TAG_NAME }}${{matrix.extension_type}}
          - os: macos-latest
            extension_type: '.exe'
            cmds_to_execute: './twilio-${{ needs.get-tag.outputs.TAG_NAME }}${{matrix.extension_type}} /S
                      sleep 100
                      $env:Path += ";C:\Program Files (x86)\twilio-cli\bin"
                      $Env:Path'
          - os: macos-latest
            extension_type: '.pkg'
            command_name: npx oclif-dev pack:macos
            cmds_to_execute: sudo installer -pkg twilio-${{ needs.get-tag.outputs.TAG_NAME }}${{matrix.extension_type}}
    steps:
       - name: Checkout cli repo
         uses: actions/checkout@v2
       - name: Perform sanity test on binaries
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
            gh release download ${{ needs.get-tag.outputs.TAG_NAME }} --pattern '*${{matrix.extension_type}}'
            ${{matrix.cmds_to_execute}}
            twilio --version
            node test/asserts/validate_tests.js
      # gh release list
         
